### ISSUE TITLE
MZ - Events RDI-RDP-WKI / DataElement: CwS - MZ - Household delivery not populated

### ISSUE THREAD

**Issue by BRaimbault** [psi-mis/connectWebapp#55]
### General description

*Client side*
On redeeming (RDI and RDP) and walk-in (WKN) events,
the data element: **CwS - MZ - Household delivery** / id: La6xS1N3YoX
should be populated with the value specified with the label: **Household delivery** (see capture below).

![1.JPG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59ad6bdd6d76bd0012828dfb/125516c66e82c728ace21e0d46b9d6d6619291a685ecbc57e607b2c1281174222a02f72d7183e52eee122b500d5c4ca446095f56e0ebcb7af8e2632dd3165eafc3674d75cf3710a9bb8217be09ba278b4e82b5aec7.JPG)

Note: The TEA **CwS - MZ - Household delivery** / id: wxAMVtMTUtp is also populated using the same source.

### To reproduce

0) Issue a voucher
1) Open: https://apps.psi-mis.org/connect-train/ with MZ_TEST_PROV / 4321
2) Press the red "+" button
3) Redeem the voucher with Pills or Injection Sayana Press as a **Service**
4) Open the corresponding record in dhis2 and see that **CwS - MZ - Household delivery** / id: La6xS1N3YoX has not been populated

**Comment by jturtler** [comment]
On Both 'redeemed' event under client, 'Household delivery' value should be put into the event data element values.
