### ISSUE TITLE
MZ - Events WKI  to be created and dataelements populated

### ISSUE THREAD

**Issue by BRaimbault** [psi-mis/connectWebapp#56]
### General description

When capturing a values for a client that does not have a match, the TEI is created but no WKI event is created (there should be one).

![2.JPG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59ad6bdd6d76bd0012828dfb/125516c66e82c728ace21e0d46bad6d6619291a685ecbc57e607b2c1281174222a02f72d7183e52eee122b500d5c4ca446095f56e0ebcb7af8e2632dd3165eafc3674d75cf3710a9bb8217be08bb27884785beaec7.JPG)

### To reproduce

1) Open: https://apps.psi-mis.org/connect-train/ with MZ_TEST_PROV / 4321
2) Press the red "+" button
3) Select the Walk In option
4) Search a client with no match
5) Submit the data without enrolling the client to CBD (eg **Service** = IUD)
6) Open the corresponding record in dhis2 and see that the TEI is created but no WKI event is created

**Comment by jturtler** [comment]
On redeem, if 'Walk In' radio button is clicked, we always want to create 'Walk In' event.
We want to populate that WalkIn Event with most of the data - which will be listed in here.

**Comment by BRaimbault** [comment]
Create event on client side 

Data elements

*Q? NO*
DE: CwS - STD - Transaction type / id:
Value: "WKI"

*Q? Service*
DE: CwS - FPL - Service received / id:
Value as specified by user

*Q? Type of user*
DE: CwS - MZ - Type of user / id: 
Value as specified by user

*Q? Household delivery*
DE: CwS - MZ - Household delivery  / id:

**Comment by jturtler** [comment]
If we implement case like mentioned above - "On redeem, if 'Walk In' radio button is clicked", 
it would mean:
  case 1: Existing Client(TEI), existing voucher found
  case 2: Existing Client(TEI), no existing voucher found
  case 3: No existing client.  Create new client(TEI) and perform redeeming..

So, are we going to create WalkIn event for all 3 cases?
The first case might not be considered as 'WalkIn'?  Since they just forgot the voucher code?

**Comment by BRaimbault** [comment]
Case3
Good point, what happens currently?

The thing is you would have to redeem if the voucher is active
Create a walkin event if the voucher is not active

Le lun. 9 juil. 2018 à 12:57, James Chang <notifications@github.com> a
écrit :

**Comment by jturtler** [comment]
Your last sentense is a bit strange... "The thing is you would have to redeem if the voucher is active Create a walkin event if the voucher is not active"

Maybe you are missing some periods & question mark?

In any case, I think you are asking the current logic of 'walkIn' case, but the found client has voucher.
In that case, WalkIn event is not created.
